Update php70.yml

diff --git a/.github/workflows/php70.yml b/.github/workflows/php70.yml
--- a/.github/workflows/php70.yml
+++ b/.github/workflows/php70.yml
@@ -9,19 +9,19 @@ on:
 jobs:
   test:
     runs-on: ${{ matrix.os }} 
-    services: 
-      mysql-db:
-        image: mysql:5.7
-        env:
-          MYSQL_ROOT_PASSWORD: 123456
-          MYSQL_DATABASE: testing_db
-        ports:
-          - 3306:3306
-        options: >-
-          --health-cmd="mysqladmin ping"
-          --health-interval=10s
-          --health-timeout=5s
-          --health-retries=3
+#    services: 
+#      mysql-db:
+#        image: mysql:5.7
+#        env:
+#          MYSQL_ROOT_PASSWORD: 123456
+#          MYSQL_DATABASE: testing_db
+#        ports:
+#          - 3306:3306
+#        options: >-
+#          --health-cmd="mysqladmin ping"
+#          --health-interval=10s
+#          --health-timeout=5s
+#          --health-retries=3
     strategy: 
       fail-fast: true
       matrix: 
@@ -34,6 +34,13 @@ jobs:
       
       - name: Clone Repo
         uses: actions/checkout@v1
+      
+      - name: Start MySQL
+        run: |
+          sudo systemctl start mysql.service
+          while ! mysqladmin ping --host=127.0.0.1 --password=123456 --silent; do
+            sleep 1
+          done
       
       - name: Setup PHP
         uses: shivammathur/setup-php@v2
